//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_field_of_work
    {
        public int company_serial { get; set; }
        public Nullable<int> work_field { get; set; }
        public Nullable<int> added_by { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
    
        public virtual company_name company_name { get; set; }
        public virtual employees_info employees_info { get; set; }
        public virtual specific_work_fields specific_work_fields { get; set; }
    }
}
