//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_person_mobile
    {
        public int sales_person_id { get; set; }
        public int branch_serial { get; set; }
        public int contact_id { get; set; }
        public int telephone_id { get; set; }
        public string mobile { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
    
        public virtual contact_person_info contact_person_info { get; set; }
    }
}
