//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees_personal_emails
    {
        public int id { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
    
        public virtual employees_info employees_info { get; set; }
    }
}
