//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class erp_systemEntities : DbContext
    {
        public erp_systemEntities()
            : base("name=erp_systemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<company_address> company_address { get; set; }
        public virtual DbSet<company_field_of_work> company_field_of_work { get; set; }
        public virtual DbSet<company_name> company_name { get; set; }
        public virtual DbSet<company_telephone> company_telephone { get; set; }
        public virtual DbSet<contact_person_info> contact_person_info { get; set; }
        public virtual DbSet<contact_person_mobile> contact_person_mobile { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<departments_type> departments_type { get; set; }
        public virtual DbSet<district> districts { get; set; }
        public virtual DbSet<educational_degrees> educational_degrees { get; set; }
        public virtual DbSet<educational_majors> educational_majors { get; set; }
        public virtual DbSet<employees_business_emails> employees_business_emails { get; set; }
        public virtual DbSet<employees_info> employees_info { get; set; }
        public virtual DbSet<employees_passwords> employees_passwords { get; set; }
        public virtual DbSet<employees_personal_emails> employees_personal_emails { get; set; }
        public virtual DbSet<generic_work_fields> generic_work_fields { get; set; }
        public virtual DbSet<positions_type> positions_type { get; set; }
        public virtual DbSet<specific_work_fields> specific_work_fields { get; set; }
        public virtual DbSet<states_governorates> states_governorates { get; set; }
        public virtual DbSet<teams_type> teams_type { get; set; }
    }
}
